version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    depends_on:
      - zookeeper
    volumes:
      - shared_data:/data  # Shared volume

  flink-jobmanager:
    image: flink:latest
    container_name: flink-jobmanager
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=flink-jobmanager
    ports:
      - "8081:8081"
    volumes:
      - shared_data:/data

  flink-taskmanager:
    image: flink:latest
    container_name: flink-taskmanager
    command: taskmanager
    depends_on:
      - flink-jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=flink-jobmanager
    volumes:
      - shared_data:/data 

  pulsar:
    image: apachepulsar/pulsar:latest
    container_name: pulsar
    command: ["bin/pulsar", "standalone"]
    ports:
      - "6650:6650"
      - "8080:8080"
    volumes:
      - shared_data:/data

  benchmarker:
    image: python:3.9
    container_name: benchmarker
    depends_on:
      - kafka
      - flink-jobmanager
      - pulsar
    volumes:
    - type: bind
      source: ./benchmark
      target: /benchmark
    - shared_data:/data 
    working_dir: /benchmark
    command: ["python", "benchmark.py"]
    build:
      context: .
      dockerfile: Dockerfile
volumes:
  shared_data:
    driver: local
