version: "3.8"
services:
  zookeeper:
    image: apachepulsar/pulsar:latest
    container_name: zookeeper
    command: bin/pulsar zookeeper
    ports:
      - "2181:2181"

  pulsar-broker:
    image: apachepulsar/pulsar:latest
    container_name: pulsar-broker
    depends_on:
      - zookeeper
    command: >
      bin/pulsar standalone
    ports:
      - "6650:6650"
      - "8080:8080"

  pulsar-init:
    image: apachepulsar/pulsar:latest
    container_name: pulsar-init
    depends_on:
      - pulsar-broker
    entrypoint: >
      /bin/bash -c "
      bin/pulsar-admin tenants create public &&
      bin/pulsar-admin namespaces create public/default &&
      bin/pulsar-admin topics create persistent://public/default/my-topic
      "
